### ISSUE TITLE
add support for blackbox installed not from flatpack

### ISSUE THREAD

**Issue by Bodyash** [ppvan/nautilus-open-in-blackbox#2]
Hello, ArchLinux user here. I'm not using flatpack and this extension is not working for me.
.py script is expecting flatpack to be installed and run blackbox from flatpack

**Comment by ppvan** [comment]
Yep. Because main distribution of BlackBox is Flatpak so i expecting every one have it
I tried to install AUR blackbox once but failed to work.
Does AUR version works for you? Add aur support is trivial (i hope) if it is stable

**Comment by Bodyash** [comment]
@ppvan yeap, AUR version works for me

**Comment by ppvan** [comment]
@Bodyash Updated. You can update the package from AUR or the install script.
