### ISSUE TITLE
doesn't work from inside samba share

### ISSUE THREAD

**Issue by 0ther0ne** [ppvan/nautilus-open-in-blackbox#6]
if I open a smb:// share in nautilus OtherLocations and try "Open in BlackBox", it doesn't work

("Open in Console" works instead)

**Comment by ppvan** [comment]
I don't think blackbox be able to connect to ftp server or something.
Console works because of strong integration with Nautilus. Can you provide more about the protocol, expected output in console?

**Comment by 0ther0ne** [comment]
if I open Console from here:

![inside this samba share](https://digilander.libero.it/luca.dm/linux/open01.png)

\
\
I get a terminal at this location:

![terminal path](https://digilander.libero.it/luca.dm/linux/open02.png)

**Comment by ppvan** [comment]
@0ther0ne  sr but i don't think i can add this.
