### ISSUE TITLE
How to translate it?

### ISSUE THREAD

**Issue by avds2** [ppvan/nautilus-open-in-blackbox#9]
Hi! I speak Persian and I want to translate nautilus-open-in-blackbox into my language. Thanks.

**Comment by ppvan** [comment]
Current version does not support i18n or l10n so you can't do it the proper way.

If you really need it, just fork this project and change [this line](https://github.com/ppvan/nautilus-open-in-blackbox/blob/c0d90c06b4c8dc765ee7e55f319dac3b27a819a5/nautilus-open-in-blackbox.py#L75) to Persian version.

https://github.com/ppvan/nautilus-open-in-blackbox/blob/c0d90c06b4c8dc765ee7e55f319dac3b27a819a5/nautilus-open-in-blackbox.py#L75

If you want this improve this project, take a look at how [nautilus-copy-path](https://github.com/chr314/nautilus-copy-path) do translation and open a Pull Request. I was really busy with my thesis right now so I can't really add this feature

**Comment by fluoriteByte** [comment]
https://github.com/ppvan/nautilus-open-in-blackbox/pull/11 adds translation support while keeping the extension as 1 file

**Comment by ppvan** [comment]
Basic support in #11
